language: generic

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - $HOME/.local/bin
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - |
    mkdir -p ~/.local/bin
    export PATH=$HOME/.local/bin:$PATH
    if ! type stack > /dev/null; then
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
    stack --no-terminal upgrade
  - stack --no-terminal --version

install:
  - travis_retry stack --no-terminal --install-ghc setup
  - stack --no-terminal exec ghc -- --version

script:
  - stack --no-terminal build
  - stack --no-terminal test
