name:       pwn
version:    '0.1.0.0'
category:   Utils
author:     Tosainu
maintainer: tosainu.maple@gmail.com
copyright:  2017 Tosainu
license:    MIT
github:     Tosainu/pwn.hs
extra-source-files:
  - README.md

flags:
  enable-ssh-client:
    manual: true
    default: false

ghc-options: -Wall

dependencies:
  - base >=4.7 && <5
  - bytestring
  - directory
  - mtl

library:
  source-dirs: src
  exposed-modules:
    - Pwn
    - Pwn.Asm
    - Pwn.Config
    - Pwn.Internal
    - Pwn.Log
    - Pwn.Packing
    - Pwn.Tubes
  other-modules:
    - Pwn.Tubes.Process
    - Pwn.Tubes.Socket
    - Pwn.Tubes.Tube
    - Util
  dependencies:
    - ansi-terminal
    - conduit
    - conduit-extra
    - exceptions
    - filepath
    - network
    - process
    - unix
  when:
    - condition: flag(enable-ssh-client)
      other-modules:
        - Pwn.Tubes.SSH
      dependencies:
        - libssh2
      cpp-options: -DENABLE_SSH_CLIENT

tests:
  pwn-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - pwn
